# Generated by Django 2.0.1 on 2018-01-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20180108_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='overall_rating',
        ),
    ]
